### ISSUE TITLE
Users lose their subscription if they change their mail

### ISSUE THREAD

**Issue by pimago** [craftcms/stripe#34]
### Description

Is it correct that users lose their subscription if they change their craft user email address?
In Stripe the subscription is still active and it knows my new email address.
Changing back to the old email address shows the subscription in Craft.

Also I am wondering if it's possible if different users could pay with the same Stripe account? For example if someone wants to pay for someone else.

### Steps to reproduce

1. Subscribe
2. Change the email of that user in Craft

**Comment by i-just** [comment]
> Is it correct that users lose their subscription if they change their craft user email address?

That’s a bug. It’s already been fixed for version 1.2, which is not yet released. For now, if you sync the customer data again (either just the customer data or all of it), you will see the user’s subscriptions again.

> Also I am wondering if it's possible if different users could pay with the same Stripe account? For example if someone wants to pay for someone else.

I’m not sure I fully understand what you’re after. Could you please provide a bit more details on what you’re trying to achieve?

**Comment by pimago** [comment]
Great. Is there an ETA when 1.2 will be released?

> I’m not sure I fully understand what you’re after. Could you please provide a bit more details on what you’re trying to achieve?

For example there are two users on Craft. User A wants to upgrade user A and B, but paying only with one Stripe account. So user B checks out and uses A's Stripe account to pay.
But I think it is not possible. Unless I would allow multiple Subscription per user on Stripe. Which would remove the ability to change the subscription tier.

**Comment by i-just** [comment]
1.2 should be out soon (as in withing a week or so, I hope).

As to your use case, you will have to check what's possible and makes most sense for you within Stripe itself. Craft's Stripe plugin exposes the API which you can use build on the integration that's available out of the box.

**Comment by pimago** [comment]
That’s great news!
I have a few other questions that I cannot figure out from the documentation.

How can I get the stripe customerid of a craft user?
How can I save content to a subscription custom field when a subscription is bought?
How can I get the customer.data.metadata.craft_user_id of a subscription in a module? 

Sorry if that’s too many questions.

**Comment by i-just** [comment]
> How can I get the stripe customerid of a craft user?

There are `getStripeCustomers()` and `getStripeCustomer()` methods on the User element. You might want to have a look at the [StripeCustomerBehavior](https://github.com/craftcms/stripe/blob/1.x/src/behaviors/StripeCustomerBehavior.php) and [Customers service](https://github.com/craftcms/stripe/blob/1.x/src/services/Customers.php) for more information.
Craft users and Stripe customers are linked by email address; keep in mind that Stripe allows multiple customers to exist with the same email address, so `StripeCustomerBehavior->getStripeCustomers()` can return multiple customers.

> How can I save content to a subscription custom field when a subscription is bought?

You might want to have a look at https://github.com/craftcms/stripe/issues/25 and the related PR (those improvements are coming in version 1.2).

> How can I get the customer.data.metadata.craft_user_id of a subscription in a module?

If you already have a user object (because, for example, that’s where you got the subscription from), you could get all customers for that user. Then, each customer model in that collection will have the `data` array that you can access. 
Other than that, you might want to have a look at the [Customers service](https://github.com/craftcms/stripe/blob/1.x/src/services/Customers.php) as there are other ways to get a customer model in the first place.

I hope this helps!

**Comment by pimago** [comment]
Thank you Iwona. That was actually very helpful.

> keep in mind that Stripe allows multiple customers to exist with the same email address

Even when I limit the customer to have only one subscription?
In which situation would Stripe create a new customer with the same email?

**Comment by lukeholder** [comment]
@pimago That setting in Stripe to limit "Limit customers to one subscription" only affects new subscriptions. We had to support multuple subscriptions belonging to the same customer. See https://docs.stripe.com/payments/checkout/limit-subscriptions


If you have that setting turned on before your site launches, you should only see one user linked to a subscription in Craft if you are using the stripe portal for subscriptions.

**Comment by pimago** [comment]
Thanks Luke. I am only wondering if multiple customers per email could be a problem with subscription grants. I am currently changing the user groups depending on which subscription a user buys or cancels. And I match this with the stripe customer id

**Comment by i-just** [comment]
Stripe 1.2.0 is out with the fix for user email changes and customer data syncing.
